### ISSUE TITLE
sean

### ISSUE THREAD

**Issue by seanfoltz** [crytic/slither-vscode#20]
Issue Type: <b>Bug</b>

issies

Extension version: 0.0.7
VS Code version: Code - Insiders 1.63.0-insider (Universal) (d18d093403b12a65350c58a7b0d5771cc1f42aba, 2021-11-26T06:34:43.820Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (1.79GB free)|
|Process Argv|-psn_0_1020153 --crash-reporter-id 1c7c2b7d-ccb9-47b6-b8c6-254cd4d94532|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30365365
pythonf5test824:30361779
javagetstartedt:30350119
pythonvspyt187:30365360
vsaa593:30376534
vsc1dst:30396469
pythonvs932:30404738
vscexrecpromptc:30397557
vscop804:30404766
vscop453:30404998

```

</details>

**Comment by broccolirob** [comment]
There's not much information here, I'm assuming this issue was created by mistake so I'm going to close it.
