### ISSUE TITLE
UI in VSCode is not working since VSCode version 1.72.2

### ISSUE THREAD

**Issue by ODeluxe** [crytic/slither-vscode#27]
Since the new update of vscode the slither ui is not working properly. You can see it in the attached image.

Here are some details about VSCode:

Version: 1.72.2
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:55.763Z (1 day ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No

![slither_ui_issue](https://user-images.githubusercontent.com/15870260/195910133-c930ed4f-af70-4dd4-8960-fcc4d080ff80.png)

**Comment by XonFire** [comment]
Hello! I've created a pull request #28 to that fixed this bug

**Comment by ODeluxe** [comment]
This fixed the issue. Thank you
