### ISSUE TITLE
Installed VS Code extension, but it can't find my slither installation

### ISSUE THREAD

**Issue by gabkov** [crytic/slither-vscode#43]
Slither works fine from the terminal, but the extension still throws the following error:

```shell
Error: Slither not found:
Please verify slither is installed with the following command: "pip install slither-analyzer"
For more information, please visit: https://github.com/crytic/slither
Refreshing explorer...
```

For some reason it can't find it. I tried both with pip and pip3 as well, also with the --user flag and tried to install Slither it from a VS Code terminal as well. I tried to install with brew too, but no success. 

macOS 13.0.1

**Comment by R-Santev** [comment]
@gabkov Did you find a way to resolve the issue?
